export { default as StarOutline } from './StarOutline'
export { default as Star } from './Star'
export { default as ThumbsUp } from './ThumbsUp'
export { default as ThumbsDown } from './ThumbsDown'
export { default as Search } from './Search'